version: '3'
services:
    mongodb:
        container_name: mongodb
        hostname: mongodb
        image: mongo
        restart: always
        ports:
          - 27017:27017
        volumes:
          - ./db:/data/db
          - ./config/configdb:/data/configdb
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
    redis:
        container_name: redis
        image: "redis:7.0.8"
        ports:
          - "6379:6379"
        volumes:
          - "./db/data/redis:/data"
          - "./config/redis:/usr/local/etc/redis"

volumes:
  mongodata:
    driver: local
  mongoconfig:
    driver: local
